### ISSUE TITLE
Excelente!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-veroena#1]
Buen trabajo @veroena !

Algunas pistas para acabarlo:

- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [ ] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [ ] mergea tu rama estupenda con master!

No te pido más porque ya has ido más allá del deber!

**Comment by veroena** [comment]
Gracias!! Me estoy viendo tu vídeo de colapsables a ver si me saco eso de que les salga un speech bubble a cada bicho... Y si se te ocurren más ideas locas, dime!

**Comment by oneeyedman** [comment]
Lo tuyo está más allá del deber!!! Excelente trabajo, @veroena
